#include "key_pair.h"
#include "domain_params.h"
#include "rng.h"

#include <stdexcept>

namespace dstu4145
{
    namespace
    {
        // A public key must be a point of order n: reject values that do not
        // decode to a curve point, the point at infinity, and points outside the
        // subgroup generated by the base point.
        auto expand_public_key(const domain_params& params, const std::vector<std::byte>& value) -> ecurve_point
        {
            const auto& curve = params.curve;
            auto q = curve.expand_point(curve.field().element(polynomial{value}));

            if (!q || *q == curve.infinity_point() || *q * params.n != curve.infinity_point())
                throw std::runtime_error("invalid public key");

            return *std::move(q);
        }
    }

    private_key::private_key(const std::vector<std::byte> &value)
        : d_{integer{value}}
    {
    }

    private_key::private_key(integer d)
        : d_{std::move(d)}
    {
    }

    public_key::public_key(const domain_params& params, const std::vector<std::byte>& value)
        : q_{expand_public_key(params, value)}
    {
    }

    public_key::public_key(const domain_params& params, const dstu4145::private_key& priv)
        : q_{-(params.p * priv)}
    {
    }
}