// std::getenv is deprecated in the MSVC CRT
#define _CRT_SECURE_NO_WARNINGS

#include <gtest/gtest.h>

#include "test-utils.h"

#include "jks.h"

#include <algorithm>
#include <cstdlib>
#include <fstream>
#include <iterator>
#include <optional>
#include <stdexcept>

namespace jks = dstu4145::jks;

using namespace testing;

namespace
{
    auto read_file(const char* path) -> dstu4145::buffer
    {
        auto file = std::ifstream{path, std::ios::binary};
        if (!file)
            throw std::runtime_error("cannot open file");

        auto result = dstu4145::buffer{};
        std::transform(std::istreambuf_iterator<char>{file}, std::istreambuf_iterator<char>{},
            std::back_inserter(result), [] (char c) { return std::byte(c); });

        return result;
    }

    // Generated by make_fixture.py. Store and key password "testpass": key entry
    // "fixture" with a two certificate chain and trusted certificate entry "ca".
    auto fixture_store() -> dstu4145::buffer
    {
        return read_file(JKS_FIXTURE);
    }

    // PKCS#8 private key on curve 6
    const auto fixture_key =
        "3045020100301E060B2A86240201010101030101300F060D2A86240201010101030101"
        "020604203E5A9B1C0C7973D0F89371D647FF5179DF0FF683010000000000000000000000";

    auto fixture_encrypted_key() -> dstu4145::buffer
    {
        return jks::load(fixture_store(), "testpass").at(0).encrypted_key;
    }

    template <class F>
    auto error_code(F f) -> std::optional<jks::errc>
    {
        try {
            f();
        } catch (const jks::error& e) {
            return e.code;
        }
        return std::nullopt;
    }
}

TEST(jks, loads_fixture)
{
    auto entries = jks::load(fixture_store(), "testpass");

    ASSERT_EQ(entries.size(), 2u);

    EXPECT_EQ(entries[0].alias, "fixture");
    EXPECT_EQ(entries[0].encrypted_key.size(), 0x84u);
    EXPECT_EQ(entries[0].certificates, (std::vector<dstu4145::buffer>{hex_buffer("3003020101"), hex_buffer("3003020102")}));

    EXPECT_EQ(entries[1].alias, "ca");
    EXPECT_TRUE(entries[1].encrypted_key.empty());
    EXPECT_EQ(entries[1].certificates, std::vector<dstu4145::buffer>{hex_buffer("3003020103")});
}

TEST(jks, decrypts_fixture_key)
{
    auto key = jks::decrypt_key(fixture_encrypted_key(), "testpass");

    EXPECT_EQ(key, hex_buffer(fixture_key));
}

TEST(jks, rejects_bad_magic)
{
    auto store = fixture_store();
    std::fill(std::begin(store), std::begin(store) + 4, std::byte{0xCE});

    EXPECT_EQ(error_code([&] { jks::load(store, "testpass"); }), jks::errc::bad_magic);
}

TEST(jks, rejects_bad_version)
{
    for (auto version : {0, 1, 3}) {
        auto store = fixture_store();
        store[7] = std::byte(version);

        EXPECT_EQ(error_code([&] { jks::load(store, "testpass"); }), jks::errc::bad_version) << version;
    }
}

TEST(jks, rejects_every_truncation)
{
    const auto store = fixture_store();

    for (auto size = std::size_t{0}; size < store.size(); ++size) {
        auto truncated = dstu4145::buffer(std::begin(store), std::begin(store) + size);

        EXPECT_EQ(error_code([&] { jks::load(truncated, "testpass"); }), jks::errc::truncated) << size;
    }
}

TEST(jks, rejects_trailing_bytes)
{
    auto store = fixture_store();
    store.push_back(std::byte{0});

    EXPECT_EQ(error_code([&] { jks::load(store, "testpass"); }), jks::errc::malformed);
}

TEST(jks, rejects_wrong_store_password)
{
    auto store = fixture_store();

    EXPECT_EQ(error_code([&] { jks::load(store, "wrongpass"); }), jks::errc::bad_store_password);
    EXPECT_EQ(error_code([&] { jks::load(store, ""); }), jks::errc::bad_store_password);
}

TEST(jks, rejects_any_flipped_byte)
{
    const auto store = fixture_store();

    for (auto i = std::size_t{0}; i < store.size(); ++i) {
        auto corrupted = store;
        corrupted[i] ^= std::byte{0x80};

        EXPECT_THROW(jks::load(corrupted, "testpass"), jks::error) << i;
    }
}

TEST(jks, rejects_wrong_key_password)
{
    auto encrypted = fixture_encrypted_key();

    EXPECT_EQ(error_code([&] { jks::decrypt_key(encrypted, "wrongpass"); }), jks::errc::bad_key_password);
    EXPECT_EQ(error_code([&] { jks::decrypt_key(encrypted, ""); }), jks::errc::bad_key_password);
}

TEST(jks, rejects_tampered_ciphertext)
{
    const auto encrypted = fixture_encrypted_key();

    // SEQUENCE header (3) + AlgorithmIdentifier (16) + OCTET STRING header (2)
    const auto payload = std::size_t{21};

    // salt, ciphertext and digest alike
    for (auto i = payload; i < encrypted.size(); ++i) {
        auto tampered = encrypted;
        tampered[i] ^= std::byte{0x01};

        EXPECT_EQ(error_code([&] { jks::decrypt_key(tampered, "testpass"); }), jks::errc::bad_key_password) << i;
    }
}

TEST(jks, rejects_malformed_key_blob)
{
    const auto encrypted = fixture_encrypted_key();
    const auto algorithm = std::string{"300E060A2B060104012A021101010500"};
    const auto zeros = [] (int count) { return std::string(count * 2, '0'); };

    auto wrong_oid = encrypted;
    wrong_oid[16] ^= std::byte{0x01};

    auto trailing = encrypted;
    trailing.push_back(std::byte{0});

    for (const auto& blob : {
        wrong_oid,
        trailing,
        hex_buffer("3012" + algorithm + "0400"),
        hex_buffer("303A" + algorithm + "0428" + zeros(40)),
        dstu4145::buffer{},
        hex_buffer("3000")
    }) {
        EXPECT_EQ(error_code([&] { jks::decrypt_key(blob, "testpass"); }), jks::errc::malformed);
    }

    // The shortest well-formed payload only fails the digest check
    auto shortest = hex_buffer("303B" + algorithm + "0429" + zeros(41));
    EXPECT_EQ(error_code([&] { jks::decrypt_key(shortest, "testpass"); }), jks::errc::bad_key_password);
}

TEST(jks, utf16_password_kat)
{
    // "parol" in Cyrillic followed by U+1F511, which takes a surrogate pair
    const auto password = "\xD0\xBF\xD0\xB0\xD1\x80\xD0\xBE\xD0\xBB\xD1\x8C\xF0\x9F\x94\x91";

    auto utf16 = jks::detail::utf16be(password);
    EXPECT_EQ(utf16, hex_buffer("043F04300440043E043B044CD83DDD11"));

    auto empty_store = hex_buffer("FEEDFEED000000020000000047D3450B70A5A571938E6ED71B3EDC51BB2CD45E");
    EXPECT_TRUE(jks::load(empty_store, password).empty());
    EXPECT_EQ(error_code([&] { jks::load(empty_store, "testpass"); }), jks::errc::bad_store_password);
}

TEST(jks, rejects_invalid_utf8_password)
{
    for (auto invalid : {
        "\x80",             // continuation byte
        "\xC0\xAF",         // overlong
        "\xC1\xBF",         // overlong
        "\xE0\x80\xAF",     // overlong
        "\xF0\x80\x80\xAF", // overlong
        "\xED\xA0\x80",     // surrogate
        "\xF4\x90\x80\x80", // above U+10FFFF
        "\xF5\x80\x80\x80",
        "\xFF",
        "\xD0",             // truncated
        "\xE2\x82",         // truncated
        "\xD0\x41"          // bad continuation
    }) {
        EXPECT_THROW(jks::detail::utf16be(invalid), std::invalid_argument);
    }

    EXPECT_THROW(jks::load(fixture_store(), "\xC0\xAF"), std::invalid_argument);
    EXPECT_THROW(jks::decrypt_key(fixture_encrypted_key(), "\xC0\xAF"), std::invalid_argument);

    EXPECT_TRUE(jks::detail::utf16be("").empty());
    auto utf16 = jks::detail::utf16be("\x7F\xC2\x80\xEF\xBF\xBF\xF4\x8F\xBF\xBF");
    EXPECT_EQ(utf16, hex_buffer("007F0080FFFFDBFFDFFF"));
}

// Runs against a real keystore when DSTU4145_JKS_PATH and DSTU4145_JKS_PASSWORD
// are set. Only sizes and single bytes are asserted so a failure never prints
// key material.
TEST(jks_local, real_keystore)
{
    const auto path = std::getenv("DSTU4145_JKS_PATH");
    const auto password = std::getenv("DSTU4145_JKS_PASSWORD");
    if (!path || !password)
        GTEST_SKIP() << "DSTU4145_JKS_PATH and DSTU4145_JKS_PASSWORD are not set";

    auto entries = jks::load(read_file(path), password);
    ASSERT_FALSE(entries.empty());

    auto keys = 0;
    for (const auto& entry : entries) {
        if (entry.encrypted_key.empty())
            continue;

        auto key = jks::decrypt_key(entry.encrypted_key, password);
        ASSERT_GT(key.size(), 2u);
        EXPECT_EQ(key[0], std::byte{0x30});
        EXPECT_FALSE(entry.certificates.empty());
        ++keys;
    }
    EXPECT_GT(keys, 0);
}
